name: Node.js CI

on:
  push:
    branches: [master, main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    needs: [get-lts]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.lts) }}

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  get-lts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      maintenance: ${{ steps.get.outputs.maintenance }}
      lts: ${{ steps.get.outputs.lts }}
      current: ${{ steps.get.outputs.current }}
      min: ${{ steps.get.outputs.min }}
